Insert into estados (id, nome, uf, regiao) values ('12', 'Acre', 'AC', 'Norte');
Insert into estados (id, nome, uf, regiao) values ('27', 'Alagoas', 'AL', 'Nordeste');
Insert into estados (id, nome, uf, regiao) values ('16', 'Amapá', 'AP', 'Norte');
Insert into estados (id, nome, uf, regiao) values ('13', 'Amazonas', 'AM', 'Norte');
Insert into estados (id, nome, uf, regiao) values ('29', 'Bahia', 'BA', 'Nordeste');
Insert into estados (id, nome, uf, regiao) values ('23', 'Ceará', 'CE', 'Nordeste');
Insert into estados (id, nome, uf, regiao) values ('53', 'Distrito Federal', 'DF', 'Centro-Oeste');
Insert into estados (id, nome, uf, regiao) values ('32', 'Espírito Santo', 'ES', 'Sudeste');
Insert into estados (id, nome, uf, regiao) values ('52', 'Goiás', 'GO', 'Centro-Oeste');
Insert into estados (id, nome, uf, regiao) values ('21', 'Maranhão', 'MA', 'Nordeste');
Insert into estados (id, nome, uf, regiao) values ('51', 'Mato Grosso', 'MT', 'Centro-Oeste');
Insert into estados (id, nome, uf, regiao) values ('50', 'Mato Grosso do Sul', 'MS', 'Centro-Oeste');
Insert into estados (id, nome, uf, regiao) values ('31', 'Minas Gerais', 'MG', 'Sudeste');
Insert into estados (id, nome, uf, regiao) values ('15', 'Pará', 'PA', 'Nordeste');
Insert into estados (id, nome, uf, regiao) values ('25', 'Paraíba', 'PB', 'Nordeste');
Insert into estados (id, nome, uf, regiao) values ('41', 'Paraná', 'PR', 'Sul');
Insert into estados (id, nome, uf, regiao) values ('26', 'Pernambuco', 'PE', 'Nordeste');
Insert into estados (id, nome, uf, regiao) values ('22', 'Piauí', 'PI', 'Nordeste');
Insert into estados (id, nome, uf, regiao) values ('33', 'Rio de Janeiro', 'RJ', 'Sudeste');
Insert into estados (id, nome, uf, regiao) values ('24', 'Rio Grande do Norte', 'RN', 'Nordeste');
Insert into estados (id, nome, uf, regiao) values ('43', 'Rio Grande do Sul', 'RS', 'Sul');
Insert into estados (id, nome, uf, regiao) values ('11', 'Rondônia', 'RO', 'Norte');
Insert into estados (id, nome, uf, regiao) values ('14', 'Roraima', 'RR', 'Norte');
Insert into estados (id, nome, uf, regiao) values ('42', 'Santa Catarina', 'SC', 'Sul');
Insert into estados (id, nome, uf, regiao) values ('35', 'São Paulo', 'SP', 'Sudeste');
Insert into estados (id, nome, uf, regiao) values ('28', 'Sergipe', 'SE', 'Nordeste');
Insert into estados (id, nome, uf, regiao) values ('17', 'Tocantins', 'TO', 'Norte');
